__Q1: Write a function so that the columns of the output matrix are powers of the input vector.__

__The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.__

__HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.__

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
N = 5

In [3]:
def atv_matrix(x, N = None, increasing = False):
    x = np.asarray(x)
    if x.ndim !=1:
        raise ValueError("a must be a one dimensional array or sequence.")
        
    if N == None:
        N = len(x)
    list_array = []
    if increasing == True:
        #x = x[::-1]
        for i in range(N):
            y = x**(N-1-i)
            list_array.append(y)
        return np.fliplr(np.stack(list_array, axis=1))
    else:
        for i in range(N):
            y = x**(N-1-i)
            list_array.append(y)
    
    return np.stack(list_array, axis=1)
    

In [4]:
atv_matrix(x,N, increasing= False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [5]:
np.vander(x,N,increasing= False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [6]:
atv_matrix(x,N, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]], dtype=int32)

In [7]:
np.vander(x,N, increasing= True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

#### Q2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence. The moving average sequence has n-k+1 elements.

In [8]:
def movingAvg(x, window):
    x = np.asarray(x)
    if x.ndim !=1:
        raise ValueError(" x must be one dimensional array or sequence")
    elif len(x) <= 1:
        return x
    elif window <= 1:
        raise ValueError("length of moving average window should be grater than 1")
    else:
        mavg = []
        for i in range(0,(len(x) - window) + 1):
            avg = np.sum(x[i: i + window])/window
            mavg.append(avg)
    return np.array(mavg)
            
            
        

In [9]:
x = [10,20,30,40,50,60,70,80,90,100]
movingAvg(x = x, window=4)

array([25., 35., 45., 55., 65., 75., 85.])

In [10]:
x = [3,5,7,2,8,10,11,65,72,81,99,100,150]
window = 3
movingAvg(x=x, window=window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])